db.url=jdbc:mysql://localhost:3306/hotel_reservation_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&tcpKeepAlive=true
db.user=root
db.password=Aniketh@223
hotel.upload.dir=
hotel.name=Grand Azure Hotel & Suites
